# Generated by Django 4.1.3 on 2024-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255, verbose_name="Fuente")),
                ("link", models.URLField(verbose_name="Enlace")),
                ("raw_text", models.TextField(verbose_name="Texto Original")),
                (
                    "preprocessed_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Preprocesado"
                    ),
                ),
            ],
            options={
                "db_table": "scrape_results",
            },
        ),
        migrations.AddField(
            model_name="cv",
            name="preprocessed_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texto preprocesado"
            ),
        ),
    ]
