# Generated by Django 4.1.3 on 2024-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0003_jobresult_remove_scraperesult_preprocessed_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="link",
            field=models.URLField(null=True, verbose_name="Enlace de Postulación"),
        ),
    ]
